language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get install expect valgrind -y
    - sudo add-apt-repository -y ppa:george-edison55/precise-backports
    - sudo apt-get update -qq
    - sudo apt-get install cmake cmake-data -y

before_script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DOCTASPIRE_DERN_COVERAGE:BOOL=ON ..

script:
    - make
      #    - valgrind --leak-check=full --error-exitcode=1 test/octaspire-dern-test-runner
    - test/octaspire-dern-test-runner -v
    - cd CMakeFiles/octaspire-dern.dir/src
    - gcov octaspire_dern_environment.c.gcno octaspire_dern_repl.c.gcno octaspire_dern_lexer.c.gcno octaspire_dern_stdlib.c.gcno octaspire_dern_port.c.gcno octaspire_dern_value.c.gcno
    - cd ../../../test/CMakeFiles/octaspire-dern-test-runner.dir/
    - gcov test_dern_vm.c.gcno
    - gcov test_dern_lexer.c.gcno
    - cd ../../../../test/REPL
    - ./octaspire-dern-repl.exp
    - cd ../../etc/
    - gcc -O3 -std=c99 -Wall -Wextra -Werror -DOCTASPIRE_DERN_AMALGAMATED_REPL_IMPLEMENTATION -DOCTASPIRE_DERN_CONFIG_BINARY_PLUGINS octaspire_dern_amalgamated.c -Wl,-export-dynamic -ldl -lm -o octaspire-dern-repl
    - echo "(println [Hello])" > hello.dern
    - ./octaspire-dern-repl hello.dern
    - clang -O3 -std=c99 -Wall -Wextra -Werror -DOCTASPIRE_DERN_AMALGAMATED_REPL_IMPLEMENTATION -DOCTASPIRE_DERN_CONFIG_BINARY_PLUGINS octaspire_dern_amalgamated.c -Wl,-export-dynamic -ldl -lm -o octaspire-dern-repl
    - ./octaspire-dern-repl hello.dern

after_success:
      - bash <(curl -s https://codecov.io/bash)

