language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get install expect -y
    - sudo add-apt-repository -y ppa:george-edison55/precise-backports
    - sudo apt-get update -qq
    - sudo apt-get install cmake cmake-data -y

before_script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DOCTASPIRE_DERN_COVERAGE:BOOL=ON ..

script:
    - make
    - test/octaspire-dern-test-runner
    - cd CMakeFiles/octaspire-dern.dir/src
    - gcov octaspire_dern_environment.c.gcno octaspire_dern_repl.c.gcno octaspire_dern_value.c.gcno octaspire_dern_lexer.c.gcno octaspire_dern_stdlib.c.gcno octaspire_dern_vm.c.gcno
    - cd ../../../../test/REPL
    - ./octaspire-dern-repl.exp

after_success:
      - bash <(curl -s https://codecov.io/bash)

