language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gdb valgrind -y; fi
      #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install valgrind; fi

before_script:
    - cd release/
    - DERN_TRAVIS_BUILD_DIR=$(pwd)

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]]; then ulimit -c unlimited -S; how-to-build/linux.sh $CC --coverage; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" != "gcc" ]]; then ulimit -c unlimited -S; how-to-build/linux.sh $CC; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then how-to-build/macOS.sh $CC; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --leak-check=full --error-exitcode=1 ./octaspire-dern-unit-test-runner --write-test-files; fi
    - ./octaspire-dern-unit-test-runner --write-test-files
      #- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]]; then gcov octaspire-dern-amalgamated.gcno; fi

after_success:
    #- cd ..
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]]; then bash <(curl -s https://codecov.io/bash) -g /usr; fi

# 'after_failure'-hook in modified form from:
# jsteemann.github.io/blog/2014/10/30/getting-core-dumps-of-failed-travisci-builds/
after_failure:
    - cd "$DERN_TRAVIS_BUILD_DIR"
    - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1)
    - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" octaspire-dern-unit-test-runner -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
