language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get install gdb expect valgrind -y

before_script:
    - cd release/
    - DERN_TRAVIS_BUILD_DIR=$(pwd)
    - ulimit -c unlimited -S
    - how-to-build/linux.sh

script:
    - $CC -O2 -std=c99 -Wall -Wextra --coverage -DOCTASPIRE_DERN_AMALGAMATED_UNIT_TEST_IMPLEMENTATION -DOCTASPIRE_DERN_CONFIG_BINARY_PLUGINS -DGREATEST_ENABLE_ANSI_COLORS -I . octaspire-dern-amalgamated.c -Wl,-export-dynamic -ldl -lm -o octaspire-dern-unit-test-runner
    - valgrind --leak-check=full --error-exitcode=1 octaspire-dern-unit-test-runner --write-test-files
    - ./octaspire-dern-unit-test-runner --write-test-files
    - gcov octaspire-dern-amalgamated.gcno

after_success:
      - bash <(curl -s https://codecov.io/bash)

# 'after_failure'-hook in modified form from:
# jsteemann.github.io/blog/2014/10/30/getting-core-dumps-of-failed-travisci-builds/
after_failure:
    - cd "$DERN_TRAVIS_BUILD_DIR"
    - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1)
    - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" octaspire-dern-unit-test-runner -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
