#ifdef __cplusplus
}
#endif

#endif // OCTASPIRE_DERN_AMALGAMATED_IMPLEMENTATION
#ifdef OCTASPIRE_DERN_AMALGAMATED_REPL_IMPLEMENTATION

#ifndef OCTASPIRE_DERN_AMALGAMATED_IMPLEMENTATION
#define OCTASPIRE_DERN_AMALGAMATED_IMPLEMENTATION 1
#endif
